on:
  push:
    tags:
      - "v*" # Push events to matching `v*` version srings. e.g. v1.0, v20.15.10

name: Create and Publish Release

jobs:
  build:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          fetch-depth: 0
          python-version: ${{ matrix.python-version }}
      - name: Install release dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Get release notes
        id: release_notes
        run: |
          git fetch --tags --force
          GITHUB_REF=${{ github.ref }}
          TAG_NAME=${GITHUB_REF/refs\/tags\//}
          echo "Got tag: $TAG_NAME"
          CHANGELOG=$(git tag -l --format='%(contents)' $TAG_NAME)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "Got changelog: $CHANGELOG"
          echo "::set-output name=changelog::$CHANGELOG"
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "${{ steps.release_notes.outputs.changelog }}"
          draft: false
          prerelease: false
      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
